### ISSUE TITLE
Assistance Desired?

### ISSUE THREAD

**Issue by Casey7747** [intelligent-agent/Recore#1]
Hi Elias,
I have been following your revolve project as I am in the process of putting a new printer together and hoped to use your controller.

How are you traveling with the latest iteration, Recore? Would you like some help?
I am very familiar with Linux, python programming/scripting + arduino + elec design at a hobby level. I am an automation engineer by profession designing programming PLC etc. So I may be of some help.

I would think helping you in testing would be my greatest assistance but I don't think you are there yet. I can also do debugging and maybe simulations?

Let me know if you think I could help.

Regards
Felix

**Comment by eliasbakken** [comment]
Hi Felix! Thanks a lot for your enthusiasm : )

To answer your question: Yes, help is needed, but it's really on the software side that you can contribute. I've put together a couple of boards so far, that are intended for some of the people that have been in the (replicape) community for a long time, so they have dibs. I'm hoping to get a small batch of around ten boards made based on their feedback and my own testing. 

I'm planning to sell the first 10 board batch for a normal price, so it's really intedid for those with a special interest in early access to the hardware. Later batches will have better software support and probably some hardware changes as well. 

Those Rev A2 boards should be going out this week, and we discuss most of the details in #development channel on replicape.slack.com

**Comment by Casey7747** [comment]
Thanks,
I have emailed you re: slack.
