### ISSUE TITLE
Hello and Setting the Recore for Printing on the Older Model Printer I have Currently...

### ISSUE THREAD

**Issue by silver2row** [intelligent-agent/Recore#3]
Hello,

Seth here. @eliasbakken and @goeland86 , this is Seth or known as silver2row on support-recore on Discord.

Anyway, enough w/ names for now. 

Can I use the 12v pin on ES0 when using GND and 3.3v on the ES5 pin specifically for the NPN Probe I use?

I am asking b/c I did not know if there was a bridge or bar of a GND on that specific side of the Recore. I do not want to catch static or error when trying to wire up like this idea on the Recore. If this does not make sense, I completely understand. I can try to better make sense in time.

...

![Recore_pinout_LI (2)](https://user-images.githubusercontent.com/9708195/141715748-fe75b3b1-9e32-4e08-a7f3-1e45f8325232.jpg)

...

I see where the ES0 connection on the wiki is 5v/12v and can be picked to either/or. But, in the photo I have listed, the ES5 pin is listed as 5v/12v.

I just want to make sure I do not alter the board state permanently by applying GND to a pin outside of its specific connector area.

Seth

P.S. Please do let me know what you have in mind from this issue. I contacted the group on Discord already. If Discord is a better place to handle this issue, that is okay too. I will just wait and try to catch someone.

**Comment by eliasbakken** [comment]
Hi Seth, 
Discord is probably better for support issues like this. This issue tracker is meant for hardware bugs with Recore boards specifically.  The numbering of the end stops were changed at some point during the development, so I think ES5 switched places with ES0 and so on. So The pinout information in the picture on the wiki is outdated. It is ES0 that has the programmable 5/12V output. 

To answer your question, the ground of all the end stops are connected together. so you can use the 12V on EN0 for triggering the input on ES5 for instance. But there should be the right number of of pins to mount an inductive sensor using only ES0. 
You mention 3.3V on the ES5, that is not correct. The output is fixed at 5V. So just be aware of that when wiring up.

**Comment by silver2row** [comment]
Hello,

Thank you for this update. And okay about the 5v output on ES5. My mistake.

Seth
