### ISSUE TITLE
[Question] What software made this pinout photo?

### ISSUE THREAD

**Issue by DjordjeMandic** [intelligent-agent/Recore#6]
Hi, im intrested which software did you use to create this pinout photo and other wiring diagrams?

![image](https://github.com/user-attachments/assets/c0e02d77-31cb-4b86-8b80-64201eebd28c)

**Comment by eliasbakken** [comment]
The board is exported from Kicad as step, then imported to Freecad where it is made into a picture and exported as png, then imported to Inkscape where the lables are added.

**Comment by DjordjeMandic** [comment]
Thanks, I thought you used something like WireViz or qelectrotech
